site_name: RGM Usage documentation
pages:
  - Home : index.md
  - Language :
    - English : en/index.md
    - Fran√ßais : fr/index.md
theme: material
repo_url: https://github.com/vfricou/docs-usage-guide.git
site_author: Vincent FRICOU <vincent@fricouv.eu>
copyright: RGM-OSC Team